function openWeaponTree(id,page=0){
 const r=CRAFT_RECIPES[id];if(!r)return;
 const children=(FORGE_CHILDREN[id]||[]),pages=Math.max(1,Math.ceil(children.length/4));page=Math.max(0,Math.min(page,pages-1));
 const node=(key,current=false)=>{
  const item=CRAFT_RECIPES[key];if(!forgeRecipeRevealed(key))return '<article class="forge-tree-node"><b>？？？</b><p>隠し派生あり。発見・解禁後に詳細表示。</p></article>';
  const equipped=forgeOwnership().filter(i=>i.key===key&&equipmentOwner(i)),issue=craftingIssue(key,craftingParents(item)[0]?.id);
  const own=forgeOwnership().some(i=>i.key===key),tags=[...buildTags({item})],before=[...buildTags({item:r})];
  return `<article class="forge-tree-node ${current?'current':''} ${issue?'':'ready'}"><small>${current?'現在見ている武器':item.awakening?'覚醒':item.parent?'派生':'基礎武器'}</small><h3>${uiEscape(item.name)}</h3><p>${item.rarity} / ${equipped.length?'装備中：'+equipped.map(i=>combatName(equipmentOwner(i))).join('・'):own?'所持済み':'未所持'}<br>${uiEscape(issue||'● 作成可能')}</p><p>${BUILD_GUIDES[item.primaryBuildTag]||''}</p>${!current?`<p>方向性：${before.map(t=>BUILD_CATALOG[t]).join('・')} → ${tags.map(t=>BUILD_CATALOG[t]).join('・')}</p>`:''}${current?'':`<button class="btn btn-sub" onclick="openWeaponTree(\'${key}\')">この先を見る</button>`}<button class="btn btn-gold" onclick="openRecipeDetail('${key}')">比較・素材・作成</button><button class="btn btn-sub" onclick="setWeaponGoal('${key}')">${normalizeWeaponGoals()[forgeFilters.character]===key?'✓ 目標設定済み':'目標にする'}</button></article>`;
 };
 const path=[],seen=new Set();let cursor=id;while(cursor&&!seen.has(cursor)){seen.add(cursor);path.unshift(cursor);cursor=CRAFT_RECIPES[cursor]?.parent;}
 const visible=forgeRecipeRevealed(id);
 showChapterModal(`${combatName(forgeFilters.character)}：武器の育成ルート`,`<nav class="forge-actions">${['player',...(state.chapter.owned.elna?['elna']:[])].map(actor=>`<button class="btn btn-sub" aria-pressed="${actor===forgeFilters.character}" onclick="forgeFilters.character='${actor}';openWeaponTree('${id}')">${renderCharacterSD(actor,{size:'small'})}</button>`).join('')}</nav><p>← 派生元 ／ 現在 ／ 派生先 →（横にスクロールできます）</p><nav class="forge-actions">${path.map(key=>forgeRecipeRevealed(key)?`<button class="btn btn-sub" onclick="openWeaponTree('${key}')">${uiEscape(CRAFT_RECIPES[key].name)}</button>`:'<span>？？？</span>').join(' → ')}</nav><div class="forge-tree-track">${r.parent?`<section><h3>← 派生元</h3>${node(r.parent)}</section>`:''}<section>${node(id,true)}</section><section><h3>派生先 → ${visible?children.length:'？'}件</h3>${visible?children.slice(page*4,page*4+4).map(n=>node(n.id)).join('')||'<p>登録済みの最終派生です。</p>':''}</section></div>${visible?weaponFuturesHtml(id):''}`,`<button class="btn btn-sub" ${!page?'disabled':''} onclick="openWeaponTree('${id}',${page-1})">前の枝</button><button class="btn btn-sub" ${page+1>=pages?'disabled':''} onclick="openWeaponTree('${id}',${page+1})">次の枝</button><button class="btn btn-sub" onclick="openCrafting()">鍛冶場へ</button><button class="btn btn-sub" onclick="closeGenericModal()">閉じる</button>`);
 document.querySelector('#modal-layer .update-notes-card')?.classList.add('forge-tree-modal');
}
