function partyMiniHtml(m){const p=characterProgress(m.id),cap=characterLevelCap(),need=characterExpRequired(p.level);return `<strong>${uiEscape(m.name)} Lv${p.level}${p.level>=cap?' MAX':''}</strong><span>HP ${Math.round(m.unit.hp)} / ${Math.round(m.stats.maxHp)}${m.unit.hp<=0?' 【'+(m.id==='player'?'敗北':'気絶')+'】':''}</span><progress aria-label="HP" value="${m.unit.hp}" max="${m.stats.maxHp}"></progress><progress aria-label="EXP" value="${p.level>=cap?need:p.exp}" max="${need}"></progress>`;}
function recommendedLevelHtml(floor=state.floor){const lv=reachedCharacterLevel(Math.max(1,floor)),current=characterProgress('player').level,diff=lv-current,label=diff<=-5?'余裕':diff<=1?'適正':diff<=4?'強敵':diff<=8?'危険':'格上';return `<small class="level-risk">⚠ 推奨Lv ${lv}〜${Math.min(50,lv+2)} / 現在Lv ${current} / ${label}（装備により変動・挑戦制限なし）</small>`;}
function nextGrowthHtml(id){const p=characterProgress(id),g=CHARACTER_GROWTH[id]||CHARACTER_GROWTH.elna;if(p.level>=characterLevelCap())return '';return `<p>次の成長：Lv${p.level} → Lv${p.level+1}<br>${[['hp','HP'],['atk','ATK'],['def','DEF']].map(([k,n])=>`${n} +${Math.floor(p.level*g[k])-Math.floor((p.level-1)*g[k])}`).join(' / ')}<br>必要EXP ${characterExpRequired(p.level)} / あと ${Math.max(0,characterExpRequired(p.level)-p.exp)} EXP</p>`;}
function openCharacterStatus(id='player'){
 const m=partyMember(id);if(!m)return;const slots=characterEquipment(id),s=m.stats,e=equipmentEffects(slots),tags=buildTags(slots);
 const detail=(name,value,text)=>`<details class="status-detail"><summary>${name}：${value}</summary><p>${text}</p></details>`;
 const content=detail('会心率',s.crit+'%','通常攻撃の会心判定。エルナは85%上限。条件付き会心は攻撃時に加算。')+detail('通常会心倍率',(id==='player'?1.8+Math.min(150,e.critDamage||0)/100:1.5+(e.critDamage||0)/100).toFixed(2)+'倍','会心が発生した通常攻撃の倍率。技ごとの計算は異なります。')+detail('行動間隔',id==='player'?'入力で1行動':'主人公に続いて1行動','速撃タグは行動間隔を短縮せず、2ヒットごとの追撃として発動します。')+detail('ガード',id==='player'?'通常55%〜30%軽減 / JUST 80%':'通常55% / JUST 80%軽減','DEF計算後に軽減。主人公は連続防御で疲労・崩壊し、最低ダメージがあります。拘束には無効。')+detail('回避',Math.min(45,e.dodge||0)+'%','装備による回避。最大45%。特殊な敵の効果で減少する場合があります。')+detail('吸血・基礎',((s.vamp||0)+(e.lifestealRate||0)+(tags.has('lifesteal')?4:0))+'%','有効ダメージ比例。条件付き補正後25%上限、ボスは半減。1回の回復は最大HPの8%まで。長期ボス戦では回復が抑制されます。')+detail('防御破壊',e.breakPower||0,'部位耐久への破壊力に加算。強攻撃では敵DEFも同値減少。breakタグは部位破壊力をさらに1.3倍。')+detail('状態異常',effectDescription(e)||'追加補正なし','装備の条件付き効果。毒・会心毒は攻撃時、タグの状態異常も命中時に判定されます。')+detail('素材補正',(e.materialChance||0)+'%','素材補助の装備値。敵・レア度の解禁条件や抽選上限は別途適用されます。')+(id==='player'?detail('ドロップ補正','レア '+s.rareRate+'% / G '+s.goldRate+'%','主人公の装備・探索補正。エルナ側の補正が自動で主人公に合算されるわけではありません。'):'');
 showChapterModal('キャラクター／ステータス',`<div class="character-tabs">${['player',...Object.keys(state.chapter.owned).filter(k=>state.chapter.owned[k])].map(k=>`<button class="btn ${id===k?'btn-gold':'btn-sub'}" onclick="openCharacterStatus('${k}')">${renderCharacterSD(k,{selected:id===k,showLevel:true})}</button>`).join('')}</div>${characterLevelHtml(id)}${nextGrowthHtml(id)}<p>現在HP ${m.unit.hp} / 最大HP ${s.maxHp}<br>ATK ${s.atk} / DEF ${s.def}${m.unit.hp<=0?' / '+(id==='player'?'敗北':'気絶'):''}</p>${content}<button class="btn btn-sub" onclick="openBuildDetails('${id}')">ビルド詳細</button><p>主要ビルド：${uiEscape([...tags].map(t=>BUILD_CATALOG[t]).join(' / ')||'なし')}</p>`,`<button class="btn btn-gold" onclick="openCharacterEquipment('${id}')">装備</button><button class="btn btn-sub" onclick="closeGenericModal()">閉じる</button>`);
}
function renderPartyStatus(){
 document.querySelectorAll('.party-summary').forEach(n=>n.remove());
 if(document.body.classList.contains('at-home'))return;
 const town=state.screen==='town',target=town?document.getElementById('lobby-screen'):state.screen!=='battle'?document.getElementById('viewport'):null;
 if(!target){if(state.screen==='battle'){const enemyCard=document.querySelector('.enemy-card');if(enemyCard&&!enemyCard.querySelector('.level-risk'))enemyCard.insertAdjacentHTML('afterbegin',recommendedLevelHtml());document.querySelectorAll('.battle-unit').forEach(n=>{if(n.dataset.combatUnit!=='enemy'){n.onclick=()=>openCharacterStatus(n.dataset.combatUnit);n.tabIndex=0;n.setAttribute('role','button');n.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();n.click();}};}});}return;}
 const members=town?['player',...Object.keys(state.chapter.owned).filter(k=>state.chapter.owned[k])].map(partyMember):activeParty();
 target.insertAdjacentHTML('afterbegin',`<div class="party-summary ${town?'party-lobby':''}">${members.map(m=>`<button onclick="openCharacterStatus('${m.id}')">${partyMiniHtml(m)}</button>`).join('')}${town?'':recommendedLevelHtml()}</div>`);
}
function showCharacterLevelUp(id,before,after){
 const g=CHARACTER_GROWTH[id]||CHARACTER_GROWTH.elna,node=document.createElement('div'),special=[10,20,30,40,50,75,100].some(l=>l>before&&l<=after);node.className='level-up-toast'+(special?' milestone':'');
 node.textContent=`${special?'✦ ':''}LEVEL UP! ${combatName(id)} Lv${before} → Lv${after}\n${[['hp','HP'],['atk','ATK'],['def','DEF']].map(([k,n])=>`${n} +${Math.floor((after-1)*g[k])-Math.floor((before-1)*g[k])}`).join(' / ')}`;document.body.append(node);setTimeout(()=>node.remove(),1800);
}
