const SummonView={tab:'gacha',name:'',rarity:'',specialty:'',sort:'rarity',page:0,selected:'mini-slime',range:1,minutes:10,timer:null};
function openSummonTutorial(){
 if(state.screen!=='town')return;clearInterval(SummonView.timer);const d=summonState();let text='',actions='';
 if(d.tutorial==='intro'){text='召喚獣は、到達済みの階層で素材を集めてくれます。未撃破のボスは突破できません。';actions='<button class="btn" onclick="summonTutorialNext()">次へ</button>';}
 if(d.tutorial==='gift'){text='最初のミニスライムは無料です。受け取って、短い派遣を体験しましょう。';actions='<button class="btn" onclick="summonFree()">ミニスライムを無料で受け取る</button>';}
 if(d.tutorial==='dispatch'){text='ミニスライムを1〜9Fへ10分派遣しましょう。初回は無料で、少なくとも素材1個を持ち帰ります。';actions='<button class="btn" onclick="startSummonDispatch(\'mini-slime\',1,10,true)">10分派遣する（無料）</button>';}
 if(d.tutorial==='waiting'){text=summonDispatchHtml(d);actions='';SummonView.timer=setInterval(()=>{const el=document.getElementById('summon-countdown');if(!el){clearInterval(SummonView.timer);return;}if(document.hidden)return;const j=summonState().jobs[0];if(j){el.textContent=summonRemaining(j);document.getElementById('summon-claim').disabled=Date.now()<j.end;}},1000);}
 if(d.tutorial==='gachaIntro'){text='素材を受け取りました！ 新しい召喚獣は単発5,000G／10連45,000Gで召喚できます。レア度で基礎効率、得意分野で集めやすい素材が変わります。';actions='<button class="btn" onclick="summonTutorialNext()">召喚画面へ</button>';}
 showChapterModal('はじめての召喚・周回',`<section id="summon-screen"><p>${text}</p></section>`,actions+'<button class="btn" onclick="closeGenericModal()">あとで（進行は保存）</button>');
}
function openSummonContract(id){
 const d=summonState(),s=SUMMONS[id],o=d.owned[id];if(!s||!o)return;
 const cost=SUMMON_CONFIG.contractCosts[o.contractLevel-1],own=Math.min(cost||0,o.stones||0),universal=((cost||0)-own)*SUMMON_CONFIG.universalPerStone;
 showChapterModal(s.name+'：契約強化',`<section id="summon-screen"><p>契約Lv${o.contractLevel}${o.contractLevel===5?' MAX':''} / 専用石 ${o.stones||0} / 汎用石 ${d.universalStones}</p><p>Lv2：得意+2pt<br>Lv3：${s.preserveNominalRewards?'速度×1.5維持（追加短縮なし）':'帰還時間−5%'}<br>Lv4：得意さらに+3pt<br>Lv5：通常敵の素材源を優先指定（50%／25%／25%）</p><p>必要専用石：1 → 2 → 3 → 5個。足りない1個を汎用石2個で代用。</p><p>${s.preserveNominalRewards?'ミコトは通常70%・レア50%・ボス35%で指定時間分の報酬を維持。速度×1.5固定、自動再派遣なし。':'実時間あたりの通常70%・レア50%・ボス35%上限は維持。上限に達する場合は時間短縮に合わせて報酬を調整。'}Lv5は数量を増やさず抽選先を変更します。</p>${o.contractLevel<5?`<p>次Lv：専用石${own}個＋汎用石${universal}個を消費</p><button class="btn" ${d.universalStones<universal?'disabled':''} onclick="summonUpgrade('${id}')">契約Lvを上げる</button>`:`<p>余剰専用石1個 → 汎用石1個</p><button class="btn" ${o.stones<1?'disabled':''} onclick="summonConvert('${id}')">1個を汎用石へ交換</button>`}</section>`,'<button class="btn" onclick="openSummons(\'codex\')">図鑑へ戻る</button>');
}
function confirmSummonDispatch(id,rangeId,minutes){
 const range=summonRanges().find(r=>r.id===rangeId),s=SUMMONS[id];if(!range||!s||!SUMMON_CONFIG.durations.includes(minutes))return;
 const fee=SUMMON_CONFIG.dispatchFees[minutes],actual=minutes*summonTimeFactor(id);
 showChapterModal('派遣の最終確認',`<section id="summon-screen"><p>${s.name} / ${range.min}〜${range.max}F</p>${summonPicture(s)}${summonTimingText(s,minutes,actual)}<p>派遣費 ${fee.toLocaleString()}G / 所持 ${state.vaultGold.toLocaleString()}G</p>${state.vaultGold<fee?'<p>Gが不足しています</p>':''}</section>`,`<button class="btn" ${state.vaultGold<fee?'disabled':''} onclick="startSummonDispatch('${id}',${rangeId},${minutes})">確定して派遣</button><button class="btn" onclick="openSummons('dispatch')">キャンセル</button>`);
}
function enhanceSummonScreen(tab){
 if(tab!=='dispatch'||summonState().jobs.length)return;const s=SUMMONS[SummonView.selected],area=AREAS.find(a=>a.id===Number(SummonView.range));if(!s||!area)return;
 const root=document.getElementById('summon-screen');root.insertAdjacentHTML('beforeend',`${summonTimingText(s,Number(SummonView.minutes))}<p>契約Lv${summonContractLevel(s.id)}。派遣中の契約強化は次回から反映。</p>`);
 if(summonContractLevel(s.id)>=5)root.insertAdjacentHTML('beforeend',`<label>優先素材源（完全指定ではありません）<select onchange="summonFocus('${s.id}',${area.id},this.value)">${summonOptions([['','均等'],...area.enemies.map(e=>[e.materialSource,e.name])],summonState().owned[s.id].focus?.[area.id]||'')}</select></label>`);
}
function summonDuration(minutes){const seconds=Math.round(minutes*60);return Math.floor(seconds/60)+'分'+(seconds%60?seconds%60+'秒':'');}
function summonTimingText(s,minutes,actual=minutes*summonTimeFactor(s.id)){return `<p>通常派遣時間：${minutes}分<br>${s.preserveNominalRewards?'ミコト補正：速度 ×1.5<br>':''}実際の完了時間：${summonDuration(actual)}<br>報酬基準：${minutes}分派遣分${s.preserveNominalRewards?'（短縮による減額なし）':'（契約Lvの時間短縮時は上限調整あり）'}</p><p>自動再派遣なし。完了後は受取・手動再派遣が必要です。</p>`;}
function summonPicture(s){return s.summonImage?`<img class="summon-picture" decoding="async" loading="lazy" src="${uiEscape(s.summonImage)}" alt="${uiEscape(s.name)}" onerror="this.hidden=true;this.nextElementSibling.hidden=false"><span hidden>🔮</span>`:'<span class="summon-picture" aria-label="画像準備中">🔮</span>';}
function summonEfficiencyText(s){return `基礎効率：通常 ${SUMMON_CONFIG.normal[s.tier]*100}% / レア ${SUMMON_CONFIG.rare[s.tier]*100}% / ボス ${Math.round(SUMMON_CONFIG.boss[s.tier]*100)}%${s.preserveNominalRewards?' / 派遣速度 ×1.5':''}`;}
function summonSpecialtyText(s){return s.specialties.map(t=>SUMMON_SPECIALTIES[t]||t).join('・')+` +${Math.round(summonSpecialtyPoints(s)*10000)/100}pt（重複加算なし・上限適用）`;}
function summonOptions(values,selected){return values.map(([id,name])=>`<option value="${uiEscape(String(id))}" ${String(id)===String(selected)?'selected':''}>${uiEscape(name)}</option>`).join('');}
function summonFilter(key,value){SummonView[key]=value;SummonView.page=0;openSummons('codex');}
function openSummons(tab=SummonView.tab){
 if(summonsUnlocked()&&summonState().tutorial!=='done')return openSummonTutorial();
 if(state.screen!=='town')return;clearInterval(SummonView.timer);SummonView.tab=tab;const d=summonState();
 const nav=`<nav class="summon-tabs">${[['gacha','召喚'],['dispatch','自動周回'],['codex','召喚獣図鑑']].map(([k,n])=>`<button class="btn ${tab===k?'active':''}" aria-pressed="${tab===k}" onclick="openSummons('${k}')">${n}</button>`).join('')}</nav>`;
 let body='';if(!summonsUnlocked())body='<p>🔒 20Fボス撃破後に解放。最初のミニスライム1体は無料です。</p>';
 else if(tab==='gacha')body=`<p>地上保管G：${state.vaultGold.toLocaleString()}G</p>${!d.freeClaimed?'<button class="btn" onclick="summonFree()">ミニスライムを無料で受け取る</button>':''}<div class="summon-actions"><button class="btn" onclick="summonGacha(1)" ${state.vaultGold<SUMMON_CONFIG.singleCost?'disabled':''}>単発 ${SUMMON_CONFIG.singleCost.toLocaleString()}G</button><button class="btn" onclick="summonGacha(10)" ${state.vaultGold<SUMMON_CONFIG.tenCost?'disabled':''}>10連 ${SUMMON_CONFIG.tenCost.toLocaleString()}G</button></div><p>基本確率：${SUMMON_CONFIG.rarities.map((r,i)=>r+' '+SUMMON_CONFIG.rates[i]*100+'%').join(' / ')}</p><p>各レア内は均等。???は600回の独立天井。???排出では既存天井をリセットしません。Abyssal300回保証に???は含みません。同時到達は???を先に保証し、Abyssal保証を次回へ繰り越します。既存天井は対応レア以上（???を除く）でリセット。</p>${Object.entries(SUMMON_CONFIG.pity).map(([tier,cap])=>`<div>${SUMMON_CONFIG.rarities[tier]}${Number(tier)<5?'以上':''}：${d.pity[tier]} / ${cap}（あと ${Math.max(1,cap-d.pity[tier])}回${d.pity[tier]>=cap?'・次回保証':''}）</div>`).join('')}<p>被りはその召喚獣の契約石×1へ変換（契約Lv強化に使用）。Gのみ使用、課金なし。</p><button class="btn" onclick="openSummonResults(summonState().history,false)">前回の召喚結果</button>`;
 else if(tab==='dispatch')body=summonDispatchHtml(d);
 else body=summonCodexHtml(d);
 showChapterModal('召喚所',`<section id="summon-screen">${nav}${body}</section>`,'<button class="btn" onclick="closeGenericModal()">ロビーへ戻る</button>');
 enhanceSummonScreen(tab);
 if(tab==='dispatch'&&d.jobs.length)SummonView.timer=setInterval(()=>{const el=document.getElementById('summon-countdown');if(!el){clearInterval(SummonView.timer);return;}if(document.hidden)return;const job=summonState().jobs[0];if(!job)return;el.textContent=summonRemaining(job);const b=document.getElementById('summon-claim');if(b)b.disabled=Date.now()<job.end;},1000);
}
function summonRemaining(job){const seconds=Math.max(0,Math.ceil((job.end-Date.now())/1000));return seconds?`残り ${Math.floor(seconds/3600)}:${String(Math.floor(seconds/60)%60).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`:'召喚獣が帰還しました';}
function summonDispatchHtml(d){
 if(d.jobs.length){const j=d.jobs[0],s=SUMMONS[j.summon];return `<h3>${uiEscape(s?.name||j.summon)}</h3>${s?summonPicture(s):''}<p>${j.range.min}〜${j.range.max}F / ${j.minutes}分</p>${s?summonTimingText(s,j.minutes,(j.end-j.start)/60000):''}<p id="summon-countdown">${summonRemaining(j)}</p><button class="btn" id="summon-claim" ${Date.now()<j.end?'disabled':''} onclick="claimSummonDispatch('${j.id}')">報酬を受け取る</button><p>受取は1回のみ。再読み込みしても報酬は再抽選されません。</p>`;}
 const owned=Object.keys(d.owned).filter(id=>SUMMONS[id]);if(!owned.length)return '<p>召喚タブから無料のミニスライムを受け取りましょう。</p>';
 if(!owned.includes(SummonView.selected))SummonView.selected=owned[0];const s=SUMMONS[SummonView.selected],ranges=summonRanges();if(!ranges.some(r=>r.id===Number(SummonView.range)))SummonView.range=ranges[0]?.id;
 const range=ranges.find(r=>r.id===Number(SummonView.range)),plans=range?summonPlans(s,range,Number(SummonView.minutes)):[],expected={normal:0,rare:0,boss:0};for(const p of plans)expected[p.kind]+=p.attempts*p.rate;
 return `<div class="summon-filters"><label>召喚獣<select onchange="SummonView.selected=this.value;openSummons('dispatch')">${summonOptions(owned.map(id=>[id,(d.owned[id].favorite?'★ ':'')+SUMMONS[id].name]),s.id)}</select></label><label>到達済み範囲<select onchange="SummonView.range=Number(this.value);openSummons('dispatch')">${summonOptions(ranges.map(r=>[r.id,`${r.min}〜${r.max}F ${r.name}`]),SummonView.range)}</select></label><label>時間<select onchange="SummonView.minutes=Number(this.value);openSummons('dispatch')">${summonOptions(SUMMON_CONFIG.durations.map(m=>[m,m+'分 '+(SUMMON_CONFIG.dispatchFees[m]?SUMMON_CONFIG.dispatchFees[m].toLocaleString()+'G':'無料')]),SummonView.minutes)}</select></label></div><h3 data-rarity-id="${s.rarityId}">${s.name} / ${s.rarity}</h3>${summonPicture(s)}<p>${summonEfficiencyText(s)}</p><p>得意：${summonSpecialtyText(s)}</p><p>予想平均（確定ではありません）：通常 ${expected.normal.toFixed(1)}個 / Rare以上 ${expected.rare.toFixed(1)}個 / ボス素材 ${expected.boss.toFixed(1)}個</p><button class="btn" ${!range?'disabled':''} onclick="confirmSummonDispatch('${s.id}',${Number(SummonView.range)},${Number(SummonView.minutes)})">派遣を確認する（${SUMMON_CONFIG.dispatchFees[SummonView.minutes].toLocaleString()}G・同時1体）</button><details><summary>計算基準・制限</summary><p>手動基準は1分＝通常敵1戦。通常素材はCommon、Rare以上は別の低い効率を使用。同じ範囲の通常敵素材を通常は均等に抽選します。契約Lv5の優先指定時は50%／25%／25%です。装備・部位破壊・エリート補正は適用しません。</p><p>最終上限：通常70% / レア50% / ボス35%。ボスは30分ごとに1機会相当、範囲内の手動撃破済みボスのみ。端数も期待値に比例。解禁前のレアリティは0%。</p><p>時計変更による完全な不正防止はできません。予定時間以上の報酬増加・自動再派遣はありません。</p></details>${d.lastRewards?'<button class="btn" onclick="openSummonRewards(summonState().lastRewards)">前回の報酬</button>':''}`;
}
function summonCodexHtml(d){
 const v=SummonView,all=Object.values(SUMMONS).filter(s=>(!v.rarity||s.rarity===v.rarity)&&(!v.specialty||(s.rarityId!=='secret'||d.owned[s.id])&&s.specialties.includes(v.specialty))&&(!v.name||d.owned[s.id]&&s.name.includes(v.name)));
 all.sort((a,b)=>v.sort==='name'?(d.owned[a.id]?a.name:'？？？').localeCompare(d.owned[b.id]?b.name:'？？？','ja'):v.sort==='favorite'?Number(!!d.owned[b.id]?.favorite)-Number(!!d.owned[a.id]?.favorite):v.sort==='efficiency'?SUMMON_CONFIG.normal[b.tier]-SUMMON_CONFIG.normal[a.tier]:b.tier-a.tier);
 const pages=Math.max(1,Math.ceil(all.length/6));v.page=Math.min(v.page,pages-1);
 return `<details class="summon-filter-panel" ${matchMedia('(orientation:landscape) and (max-height:540px) and (max-width:1100px)').matches?'':'open'}><summary>検索・絞り込み・並び順</summary><div class="summon-filters"><label>名前<input value="${uiEscape(v.name)}" onchange="summonFilter('name',this.value)" placeholder="取得済みを検索"></label><label>レア度<select onchange="summonFilter('rarity',this.value)">${summonOptions([['','すべて'],...SUMMON_CONFIG.rarities.map(r=>[r,r])],v.rarity)}</select></label><label>得意<select onchange="summonFilter('specialty',this.value)">${summonOptions([['','すべて'],...Object.entries(SUMMON_SPECIALTIES)],v.specialty)}</select></label><label>並び順<select onchange="summonFilter('sort',this.value)">${summonOptions([['rarity','レア度'],['efficiency','通常効率'],['name','名前'],['favorite','お気に入り優先']],v.sort)}</select></label></div></details><div class="summon-grid">${all.slice(v.page*6,v.page*6+6).map(s=>d.owned[s.id]?`<article data-rarity-id="${s.rarityId}">${summonPicture(s)}<b>${s.name}</b><div>${s.rarity}</div><p>${summonEfficiencyText(s)}</p><p>得意：${summonSpecialtyText(s)}</p><p>${s.features}</p><small>契約Lv${d.owned[s.id].contractLevel} / 契約石 ${d.owned[s.id].stones||0}個</small><button class="btn" onclick="openSummonContract('${s.id}')">契約強化・石交換</button><button class="btn" aria-pressed="${!!d.owned[s.id].favorite}" onclick="summonFavorite('${s.id}')">${d.owned[s.id].favorite?'★ お気に入り済み':'☆ お気に入り'}</button><button class="btn" onclick="SummonView.selected='${s.id}';openSummons('dispatch')">派遣設定へ</button></article>`:`<article data-rarity-id="${s.rarityId}"><span class="summon-undiscovered">未発見</span><b>？？？</b><p>${s.rarity} / 未取得</p><p>能力：？？？<br>説明：？？？<br>得意：？？？</p></article>`).join('')}</div><div class="summon-actions"><button class="btn" ${v.page<=0?'disabled':''} onclick="SummonView.page--;openSummons('codex')">前へ</button><span>${v.page+1} / ${pages}（${all.length}体）</span><button class="btn" ${v.page>=pages-1?'disabled':''} onclick="SummonView.page++;openSummons('codex')">次へ</button></div>`;
}
function skipSummonReveal(){document.querySelector('.summon-reveal')?.classList.remove('summon-reveal');document.querySelector('.summon-secret-stage')?.remove();}
function openSummonResults(results,animate=false){
 const secret=animate&&results.some(r=>SUMMONS[r.id]?.rarityId==='secret');
 const stage=secret?`<div class="summon-secret-stage" aria-hidden="true"><div class="summon-moon"></div><div class="summon-petals">${Array.from({length:6},(_,i)=>`<i style="--petal:${i}"></i>`).join('')}</div><div class="summon-foxfire"></div><strong>???<br>桜月天狐・ミコト</strong></div>`:'';
 showChapterModal('召喚結果',`<div class="summon-results">${stage}<div class="summon-grid ${animate?'summon-reveal':''}">${results.map(r=>{const s=SUMMONS[r.id];return `<article data-rarity="${s.rarity}" data-rarity-id="${s.rarityId}">${summonPicture(s)}<b>${s.name}</b><div>${s.rarity}</div><p>${r.duplicate?'被り → 契約石 +1':'新しい契約！'}</p></article>`;}).join('')}</div></div>`,'<button class="btn" onclick="openSummons(\'gacha\')">確認して戻る</button><button class="btn" onclick="skipSummonReveal()">演出スキップ</button>');
}
function openSummonRewards(rewards){const s=SUMMONS[summonState().lastRewardSummon];showChapterModal('召喚獣が帰還しました',`${s?summonPicture(s)+'<b>'+s.name+'</b>':''}<p>倉庫へ保管済み</p>${Object.entries(rewards).map(([k,n])=>`<p>${uiEscape(MATERIALS[k]?.name||k)} ×${n} / ${MATERIALS[k]?.rarity||''}</p>`).join('')||'<p>今回は素材を発見できませんでした。</p>'}`,'<button class="btn" onclick="openSummons(\'dispatch\')">派遣画面へ</button>');}
const summonLobbyBase=syncLobbyScreen;
syncLobbyScreen=function(){summonLobbyBase();const menu=document.querySelector('#lobby-screen .lobby-menu');if(menu&&!menu.querySelector('[data-summons]'))menu.insertAdjacentHTML('beforeend','<button data-summons onclick="openSummons()">召喚・周回</button>');};
